// Translations (expand as needed)
const translations = {
    fr: {
        subtitle: "LABORATOIRE DE RECHERCHE & DÉVELOPPEMENT",
        "hero-title": "Laboratoire d'Innovation en Data & IA",
        "accent-text": "Data & IA",
        description: "Nous sommes spécialisés dans la modélisation prédictive et l'analyse de données complexes (géospatiales, financières, etc.). Notre mission est d'optimiser les stratégies d'entreprise par des solutions d'Intelligence Artificielle rigoureuses et sur mesure. Déterminée à redéfinir les standards par la rigueur du code et l'excellence de l'analyse.",
        "case-studies-btn": "Accéder aux Études de Cas",
        "collaborate-btn": "Démarrer une Collaboration",
        "case-studies-title": "Nos Solutions Prouvées",
        "case-studies-subtitle": "Démontrer la rigueur technique et l'impact de l'Intelligence Artificielle.",
        "nasa-title": "Hackathon NASA : Projet GaiaByte – Climat Insights",
        tag1: "Analyse Géospatiale (SIG)",
        tag2: "Google Earth Engine (GEE)",
        tag3: "Télédétection",
        "nasa-desc": "Participation à un défi d'innovation intense (Hackathon NASA, Octobre 2025). Ce projet visait à modéliser l'impact des variations climatiques en utilisant des données satellites (Landsat/SRTM). <br><br><strong>Rôle et Impact :</strong> J'ai géré le volet d'analyse géospatiale, utilisant <strong>Google Earth Engine (GEE) et Python</strong> pour traiter rapidement des volumes importants de données de télédétection. Le défi était de livrer une solution fonctionnelle en 48 heures, démontrant ma <strong>rigueur en SIG</strong> et ma capacité à la <strong>gestion de projet</strong> sous contrainte.",
        "github-btn": "Voir le code source (GitHub)",
        "cs50-title": "Certification CS50 (HarvardX) : Maîtrise des Fondamentaux de l'Informatique",
        tag4: "Python",
        tag5: "C & Algorithmique",
        tag6: "SQL & Bases de Données",
        "cs50-desc": "Certification démontrant la maîtrise des concepts fondamentaux de l'informatique. J'ai acquis les bases solides en algorithmique, en langages C et Python, et en bases de données SQL. <br><br><strong>Démonstration :</strong> La validation de CS50 prouve ma capacité à écrire du <strong>code propre et performant</strong> pour la résolution de problèmes, un socle essentiel pour l'Intelligence Artificielle et la Data Science.",
        "project-btn": "Accéder au Projet",
        "services-title": "🚀 Services & Offres Partenaires",
        "services-desc": "Nous développons actuellement une structure de conseil sur mesure.<br>Revenez bientôt pour découvrir comment la Data et l'IA peuvent transformer votre business.",
        "back-btn": "Retour à l'Accueil",
        "affiliate-text": "Recommandé: Livre sur l'IA pour Débutants (Gagnez des commissions sur les achats)",
        "donate-btn": "Soutenez Veritasia - À partir de 1$"
    },
    en: {
        subtitle: "RESEARCH & DEVELOPMENT LABORATORY",
        "hero-title": "Innovation Laboratory in Data & AI",
        "accent-text": "Data & AI",
        description: "We specialize in predictive modeling and complex data analysis (geospatial, financial, etc.). Our mission is to optimize business strategies through rigorous and customized Artificial Intelligence solutions. Committed to redefining standards through code rigor and analytical excellence.",
        "case-studies-btn": "Access Case Studies",
        "collaborate-btn": "Start a Collaboration",
        "case-studies-title": "Our Proven Solutions",
        "case-studies-subtitle": "Demonstrating technical rigor and the impact of Artificial Intelligence.",
        "nasa-title": "NASA Hackathon: GaiaByte Project – Climate Insights",
        tag1: "Geospatial Analysis (GIS)",
        tag2: "Google Earth Engine (GEE)",
        tag3: "Remote Sensing",
        "nasa-desc": "Participation in an intense innovation challenge (NASA Hackathon, October 2025). This project aimed to model the impact of climate variations using satellite data (Landsat/SRTM). <br><br><strong>Role and Impact:</strong> I managed the geospatial analysis aspect, using <strong>Google Earth Engine (GEE) and Python</strong> to quickly process large volumes of remote sensing data. The challenge was to deliver a functional solution in 48 hours, demonstrating my <strong>GIS rigor</